<a href="https://colab.research.google.com/github/larisamakhynia-svg/python-analytics-homework/blob/main/PROEKT_2_Makhynia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('survey_results_public.csv')
df1 = pd.read_csv('survey_results_schema.csv')

/tmp/ipykernel_905/2048986362.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('survey_results_public.csv')

In [ ]:
df = pd.read_csv('survey_results_public.csv', low_memory=False)
df1 = pd.read_csv('survey_results_schema.csv')
print(f"Завантажено рядків: {df.shape[0]}")
df.head()

Завантажено рядків: 49191

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [ ]:
# Завдання 1. Підрахунок загальної кількості респондентів перший спосіб

total_respondents = df.shape[0]
total_respondents

49191

In [ ]:
# Завдання 1. Підрахунок загальної кількості респондентів другий спосіб

total_respondents = df['ResponseId'].nunique()
total_respondents

49191

In [ ]:
# Завдання 2. Аналіз повноти відповідей респондентів

questions_set = set(df1['qname'].unique())
common_columns = list(questions_set.intersection(df.columns))
clean_df = df.dropna(subset=common_columns)
total_complete = clean_df.shape[0]

print(f"Кількість респондентів, які відповіли на всі питання: {total_complete}")

Кількість респондентів, які відповіли на всі питання: 0

In [ ]:
# Завдання 3. Статистичний аналіз досвіду респондентів

work_exp_mean = df['WorkExp'].mean()
work_exp_median = df['WorkExp'].median()
work_exp_mode = df['WorkExp'].mode()[0]

print(f"Міри центральної тенденції для WorkExp:")
print(f"Середнє значення: {work_exp_mean:.1f}")
print(f"Медіана:          {work_exp_median}")
print(f"Мода:             {work_exp_mode}")

Міри центральної тенденції для WorkExp:
Середнє значення: 13.4
Медіана:          10.0
Мода:             10.0

In [ ]:
# Завдання 4. Аналіз віддаленої роботи
df['RemoteWork'].unique()

array(['Remote', 'Hybrid (some in-person, leans heavy to flexibility)',
       nan, 'In-person', 'Hybrid (some remote, leans heavy to in-person)',
       'Your choice (very flexible, you can come in when you want or just as needed)'],
      dtype=object)

In [ ]:
remote_workers = df[df['RemoteWork'] == 'Remote']
remote_count = remote_workers.shape[0]
remote_count

10931

In [ ]:
# Завдання 5. Визначення популярності Python

df['worked_with_python'] = df['LanguageHaveWorkedWith'].str.contains('Python', na=False)
python_users_count = df['worked_with_python'].sum()
total_respondents = len(df)
python_percentage = (python_users_count / total_respondents) * 100

print(f"Відсоток респондентів: {python_percentage:.1f}%")

Відсоток респондентів: 37.5%

In [ ]:
# Завдання 6. Аналіз шляхів навчання програмуванню

df['Learned_with_online_courses'] = df['LearnCode'].str.contains('Online Courses', na=False)
online_learners_count = df['Learned_with_online_courses'].sum()

print(f"Кількість респондентів, що навчалися через онлайн-курси: {online_learners_count}")

Кількість респондентів, що навчалися через онлайн-курси: 10973

In [ ]:
#Завдання 7. Географічний аналіз компенсації Python-розробників

python_devs = df[df['worked_with_python'] == True].dropna(subset=['ConvertedCompYearly'])
py_progers_by_country = python_devs.groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median'])
py_progers_by_country

                                               mean    median
Country
Afghanistan                            22328.666667    1000.0
Albania                                47217.600000   50000.0
Algeria                                20187.285714    7088.0
Andorra                               226103.500000  226103.5
Antigua and Barbuda                        1.000000       1.0
...                                             ...       ...
Venezuela, Bolivarian Republic of...    9908.647059    3000.0
Viet Nam                              218837.166667    8254.0
Yemen                                  32929.500000   23672.0
Zambia                                  5424.250000    3206.0
Zimbabwe                               34000.000000   25500.0

[153 rows x 2 columns]

In [ ]:
# Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

top_paid_df = df[['ResponseId', 'EdLevel', 'ConvertedCompYearly']]
top_paid_df = top_paid_df.sort_values(by='ConvertedCompYearly', ascending=False)
top_paid_df = top_paid_df.reset_index(drop=True)
top_5_paid = top_paid_df.head(5)
top_5_paid

,ResponseId,EdLevel,ConvertedCompYearly
0,34268,"Associate degree (A.A., A.S., etc.)",50000000.0
1,28701,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",33552715.0
2,43144,"Associate degree (A.A., A.S., etc.)",18387548.0
3,35354,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",15430267.0
4,45972,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",13921760.0

In [ ]:
# Завдання 9. Аналіз популярності Python по віковим категоріям

age_python_stats = df.groupby('Age')['worked_with_python'].mean() * 100
age_python_stats = age_python_stats.reset_index()
age_python_stats.columns = ['Вікова категорія', 'Відсоток Python-розробників']
age_python_stats['Відсоток Python-розробників'] = age_python_stats['Відсоток Python-розробників'].round(1)
age_python_stats

    Вікова категорія  Відсоток Python-розробників
0    18-24 years old                         40.0
1    25-34 years old                         36.9
2    35-44 years old                         36.7
3    45-54 years old                         38.6
4    55-64 years old                         37.2
5  65 years or older                         31.6
6  Prefer not to say                         31.2

In [ ]:
# Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників


income_threshold = df['ConvertedCompYearly'].quantile(0.75)
high_paid_remote = df[
    (df['ConvertedCompYearly'] > income_threshold) &
    (df['RemoteWork'] == 'Remote')
]
high_paid_remote_industries = high_paid_remote['Industry'].dropna()
industry_counts = high_paid_remote_industries.value_counts()

print(f"75-й перцентиль компенсації: {income_threshold:.0f}")
print("-" * 30)
print("Найпопулярніші індустрії серед високооплачуваних віддалених працівників:")
industry_counts.head(10)

75-й перцентиль компенсації: 120596
------------------------------
Найпопулярніші індустрії серед високооплачуваних віддалених працівників:

Industry
Software Development                          1186
Fintech                                        190
Healthcare                                     188
Other:                                         176
Internet, Telecomm or Information Services     138
Banking/Financial Services                      88
Government                                      78
Media & Advertising Services                    75
Retail and Consumer Services                    65
Transportation, or Supply Chain                 63
Name: count, dtype: int64